config/routes.rb
resources :html_blocks

app/models/html_block.rb
class HtmlBlock < ActiveRecord::Base
  def self.render_blocks(path)
    where('exact_path = ? OR ? LIKE pattern_path', path, path)
  end
end

app/controllers/html_blocks_controller.rb
class HtmlBlocksController < ApplicationController
  before_action :set_html_block, only: [:show, :edit, :update, :destroy]

  def index
    @html_blocks = HtmlBlock.all
  end

  def show; end

  def new
    @html_block = HtmlBlock.new
  end

  def edit; end

  def create
    @html_block = HtmlBlock.new(html_block_params)

    respond_to do |format|
      if @html_block.save
        format.html do
          redirect_to html_blocks_url, notice: 'Block was created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @html_block.update(html_block_params)
        format.html do
          redirect_to html_blocks_url, notice: 'HtmlBlock was updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @html_block.destroy
    respond_to do |format|
      format.html do
        redirect_to html_blocks_url, notice: 'HtmlBlock was destroyed.'
      end
    end
  end

  private

  def set_html_block
    @html_block = HtmlBlock.find(params[:id])
  end

  def html_block_params
    params.require(:html_block).permit(:html_content, :exact_path,
                                       :pattern_path)
  end
end

app/helpers/html_blocks_helper.rb
module HtmlBlocksHelper
end

app/views/html_blocks/_form.html.erb
<%= form_for(block) do |f| %>

    <h3>Exact path:</h3>
    <%= f.text_field :exact_path %>

    <h3>Pattern path(example: %path, %path%, path%):</h3>
    <%= f.text_field :pattern_path %>

    <h3>Html content:</h3>
    <%= f.text_area :html_content, rows: 10, cols: 60 %>
    <br/>

    <%= f.submit %>
<% end %>

app/views/html_blocks/_html_blocks.html.erb
<% HtmlBlock.render_blocks(request.original_fullpath).each do |block| %>
  <%= block.html_content.html_safe %>
<% end %>

app/views/html_blocks/edit.html.erb
<h1>Editing HtmlBlock</h1>

<%= render 'form', block: @html_block %>

app/views/html_blocks/index.html.erb
<h1>Html Blocks</h1>

<table>
  <thead>
    <tr style="text-align: left">
      <th>Html content</th>
      <th>Exact path</th>
      <th>Pattern path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @html_blocks.each do |html_block| %>
      <tr>
        <td><%= truncate html_block.html_content %></td>
        <td><%= truncate html_block.exact_path %></td>
        <td><%= truncate html_block.pattern_path %></td>
        <td><%= link_to 'Show', html_block %></td>
        <td><%= link_to 'Edit', edit_html_block_path(html_block) %></td>
        <td><%= link_to 'Destroy', html_block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Html Block', new_html_block_path %>

app/views/html_blocks/new.html.erb
<h1>New HtmlBlock</h1>

<%= render 'form', block: @html_block %>

<%= link_to 'Back', html_blocks_path %>

app/views/html_blocks/show.html.erb
<p>
  <strong>ExactPath:</strong>
  <%= @html_block.exact_path %>
</p>

<p>
  <strong>PatternPath:</strong>
  <%= @html_block.pattern_path %>
</p>

<p>
  <strong>HtmlContent:</strong>
  <%= @html_block.html_content %>
</p>

<%= link_to 'Edit', edit_html_block_path(@html_block) %> |
<%= link_to 'Back', html_blocks_path %>